# Generated by Django 4.2.19 on 2025-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_monwidgetsconnections_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pinned_databases',
            field=models.JSONField(default=list),
        ),
    ]
