# Generated by Django 4.2.23 on 2025-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_monwidgetsconnections_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monwidgets',
            name='script_chart',
            field=models.TextField(blank=True, default=''),
        ),
    ]
