# Generated by Django 4.2.19 on 2025-07-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_connection_pinned_databases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERDLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layout', models.JSONField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.connection')),
            ],
            options={
                'unique_together': {('connection', 'name')},
            },
        ),
    ]
