# Generated by Django 4.2.23 on 2025-08-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_monwidgets_script_chart'),
        ('app', '0027_erdlayout'),
    ]

    operations = [
    ]
