# Generated by Django 4.2.23 on 2025-09-04 13:53

from django.db import migrations
from django.contrib.sessions.models import Session

def migrate_sessions(apps, schema_editor):
    if not apps.is_installed("sessions"):
        return
    
    for s in Session.objects.all():
        data = s.get_decoded()

        pgmanage_session = data.get("pgmanage_session")
        if pgmanage_session is None:
            continue

        # detect old pickled Session object
        if hasattr(pgmanage_session, "v_user_id"):
            s.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_merge_20250821_0702'),
    ]

    operations = [
        migrations.RunPython(migrate_sessions, migrations.RunPython.noop)
    ]
