# Generated by Django 4.2.23 on 2025-09-05 12:47

from django.db import migrations

def populate_technologies(apps, schema_editor):
    Technology = apps.get_model('app', 'Technology')
    Technology(name='mssql').save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20250904_1353'),
    ]

    operations = [
        migrations.RunPython(populate_technologies)
    ]
