# Generated by Django 4.2.23 on 2025-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_populate_mssql-technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='show_system_catalogs',
            field=models.BooleanField(default=False),
        ),
    ]
